version: "3.8"
services:
  mysqldb:
    image: "mysql:8.0"
    container_name: mysqldb-etiqa
    restart: always
    ports:
      - "${MYSQL_PORT_MAP}:3306"
    networks:
      - local_network
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      
  api_service:
    container_name: onlinestore-etiqa
    build: .
    restart: always
    ports:
      - ${APP_PORT_MAP}:8080
    networks:
      - local_network
    environment:
      - spring.datasource.url=jdbc:mysql://mysqldb-etiqa:3306/${MYSQL_DATABASE}?allowPublicKeyRetrieval=true&useSSL=false
    depends_on:
      - mysqldb
    volumes:
      - .m2:/root/.m2
      


networks:
  local_network:
    name: ${NETWORK}
    driver: bridge
